import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div className=" flex-column w-full h-full">
      {/* <Head>
        <title>To-do List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <Navbar />

      <main className="h-full w-full flex flex-row">
        <Sidebar />
        <div className="w-full md:w-5/6 bg-gray-800 h-screen overflow-hidden flex justify-center items-center text-white">
          {" "}
          This is our center container..
        </div>
      </main>
    </div>
  );
}
